name: 🐞 Bug Report
description: Create a report to help us improve
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Note: the following is not mandatory, just a guideline. Feel free to describe your bug report or suggestion in another way.
  - type: textarea
    id: background
    attributes:
      label: Description
      description: Please provide a succinct description of your issue.
      placeholder: Description
    validations:
      required: true
  - type: textarea
    id: known-workarounds
    attributes:
      label: Known Workarounds
      description: Please provide a description of any known workarounds.
      placeholder: Known Workarounds
    validations:
      required: false
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Provide a description of the expected behavior.
      placeholder: Expected behavior
    validations:
      required: false
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: |
        Provide a description of the actual behavior observed. If applicable please include any error messages or exception stack-traces.
      placeholder: Actual behavior
    validations:
      required: false
  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: |
        Please provide more information on your .NET configuration:
          * Operating system
          * Branch/Version
          * .NET Runtime, CoreCLR or Mono Version
          * Performance information, links to performance testing scripts
      placeholder: Configuration
    validations:
      required: false
  - type: textarea
    id: repro-steps
    attributes:
      label: Reproduction Steps
      description: |
        Please include minimal steps to reproduce the problem if possible. E.g.: the smallest possible code snippet; or a small project, with steps to run it.
        Always include text as text rather than screenshots so code can easily be copied and will show up in searches.
        Stack Overflow has a great article about [how to create a minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
      placeholder: Minimal Reproduction
    validations:
      required: false
  - type: dropdown
    id: pull-request
    attributes:
      label: Are you willing to help with a pull-request?
      description: |
        Make sure you have read the sections about [contributing changes](https://github.com/fsprojects/FSharpPlus/blob/master/DEVELOPER_GUIDE.md) and [design guidelines](https://github.com/fsprojects/FSharpPlus/blob/master/DESIGN_GUIDELINES.md). 
      options:
        - "No"
        - "Yes, please assign this issue to me."
    validations:
      required: true
