// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("FSharpPlus.BaseLib")]
[assembly: AssemblyProductAttribute("FSharpPlus")]
[assembly: AssemblyDescriptionAttribute("F#+ is an overload library for F#.")]
[assembly: AssemblyVersionAttribute("1.0.4")]
[assembly: AssemblyFileVersionAttribute("1.0.4")]
[assembly: AssemblyConfigurationAttribute("Release")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "FSharpPlus.BaseLib";
        internal const System.String AssemblyProduct = "FSharpPlus";
        internal const System.String AssemblyDescription = "F#+ is an overload library for F#.";
        internal const System.String AssemblyVersion = "1.0.4";
        internal const System.String AssemblyFileVersion = "1.0.4";
        internal const System.String AssemblyConfiguration = "Release";
    }
}
