// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharpPlus")>]
[<assembly: AssemblyProductAttribute("FSharpPlus")>]
[<assembly: AssemblyDescriptionAttribute("F#+ is an overload library for F#.")>]
[<assembly: AssemblyVersionAttribute("1.0.4")>]
[<assembly: AssemblyFileVersionAttribute("1.0.4")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharpPlus"
    let [<Literal>] AssemblyProduct = "FSharpPlus"
    let [<Literal>] AssemblyDescription = "F#+ is an overload library for F#."
    let [<Literal>] AssemblyVersion = "1.0.4"
    let [<Literal>] AssemblyFileVersion = "1.0.4"
    let [<Literal>] AssemblyConfiguration = "Release"
