// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharpPlus")>]
[<assembly: AssemblyProductAttribute("FSharpPlus")>]
[<assembly: AssemblyDescriptionAttribute("F#+ is a library with extensions for F# based on FsControl.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharpPlus"
    let [<Literal>] AssemblyProduct = "FSharpPlus"
    let [<Literal>] AssemblyDescription = "F#+ is a library with extensions for F# based on FsControl."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
    let [<Literal>] AssemblyConfiguration = "Release"
